cargo_index:
    path:     /{id}
    defaults: { _controller: "SiafcaIntranetBundle:Cargo:index" }
    methods:  GET

cargo_show:
    path:     /{id}/show
    defaults: { _controller: "SiafcaIntranetBundle:Cargo:show" }
    methods:  GET

cargo_new:
    path:     /new
    defaults: { _controller: "SiafcaIntranetBundle:Cargo:new" }
    methods:  [GET, POST]

cargo_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiafcaIntranetBundle:Cargo:edit" }
    methods:  [GET, POST]

cargo_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiafcaIntranetBundle:Cargo:delete" }
    methods:  DELETE
