<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * AyudaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyudaRepository extends \Doctrine\ORM\EntityRepository
{
}
