<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * BoletaDepositoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletaDepositoRepository extends \Doctrine\ORM\EntityRepository
{
}
