<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends \Doctrine\ORM\EntityRepository
{
    public function cargosportipoorganismotodos($tipoorgId, $offset, $limite){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '.
                    'c '.
                'FROM '.
                    'SiafcaIntranetBundle:Cargo c '.
                'WHERE '.
                    'c.tipoOrganismo = :tipoorg '.
                'ORDER BY '.
                    'c.nombre ASC '
                )->setParameter('tipoorg', $tipoorgId)
                ->setFirstResult($offset)
                ->setMaxResults($limite)                
                ->getResult();
        
        return $query;
        
    }
    
     public function cargosportipoorganismoapp($tipoorgId, $or, $offset, $limite){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '.
                    'c '.
                'FROM '.
                    'SiafcaIntranetBundle:Cargo c '.
                'WHERE '.
                    'c.tipoOrganismo = :tipoorg '.
                    'AND c.origen = ?1'. 
                'ORDER BY '.
                    'c.nombre ASC '
                )->setParameter('tipoorg', $tipoorgId)
                 ->setParameter(1, $or)
                 ->setFirstResult($offset)
                 ->setMaxResults($limite)                              
                 ->getResult();
        
        return $query;
        
    }
    
    public function cargosTipoOrganismoCodigo($tipoorganismo, $origen, $codigo, $offset, $limite ){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '.
                    'c '.
                'FROM '.
                    'SiafcaIntranetBundle:Cargo c '.
                'WHERE '.
                    'c.tipoOrganismo = :tipoorg '.
                    'AND c.origen = ?1 '.
                    'AND c.codigo = :cod '.
                'ORDER BY '.
                    'c.nombre ASC '
                )->setParameter('tipoorg', $tipoorganismo)
                ->setParameter('cod', $codigo)
                ->setParameter(1, $origen)
                ->setFirstResult($offset)
                ->setMaxResults($limite)                
                ->getResult();
        
        return $query;
    }
    
    public function cargosTipoOrganismoNombre($tipoorganismo, $origen, $nombre, $offset, $limite ){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '.
                    'c '.
                'FROM '.
                    'SiafcaIntranetBundle:Cargo c '.
                'WHERE '.
                    'c.tipoOrganismo = :tipoorg '.
                    'AND c.origen = ?1 '.
                    'AND upper(c.nombre) LIKE :nombre '.
                'ORDER BY '.
                    'c.nombre ASC '
                )->setParameter('tipoorg', $tipoorganismo)
                ->setParameter('nombre', '%' . $nombre . '%')
                ->setParameter(1, $origen)
                ->setFirstResult($offset)
                ->setMaxResults($limite)                
                ->getResult();
        
        return $query;
    }
}
