<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ClaseLiquidacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseLiquidacionRepository extends \Doctrine\ORM\EntityRepository
{
}
