<?php

namespace Caja\SiafcaIntranetBundle\Repository;

use Caja\SiafcaIntranetBundle\Entity\ConceptoItem;

/**
 * ConceptoItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param array[] $conceptoItemArray
     * @return ConceptoItem
     */
    public function crearConceptoItem($conceptoItemArray)
    {
        $em = $this->getEntityManager();
        $concepto = $em->getRepository('SiafcaIntranetBundle:Concepto')->find($conceptoItemArray['concepto']['id']);
        $conceptoItem = new ConceptoItem();
        $conceptoItem->setConcepto($concepto);
        $conceptoItem->setImporte($conceptoItemArray['importe']);
        if($conceptoItemArray['porcentaje'] != null)
            $conceptoItem->setPorcentaje($conceptoItemArray['porcentaje']);
        else $conceptoItem->setPorcentaje(0);
        
        return $conceptoItem;
    }
    
    /**
     * Actualiza los valores de una instancia de ConceptoItem, o crea una nueva
     * @param array[] $conceptoItemArray
     * @return ConceptoItem
     */
    public function updateOrCreateConceptoItem($conceptoItemArray)
    {
        $em = $this->getEntityManager();
        if (!$conceptoItemArray['id']) {
            return $this->crearConceptoItem($conceptoItemArray);
        }
        $conceptoItem = $em->getRepository('SiafcaIntranetBundle:ConceptoItem')->find($conceptoItemArray['id']);
        if ($conceptoItem->getConcepto()->getId() != $conceptoItemArray['concepto']['id']) {
            $concepto = $em->getRepository('SiafcaIntranetBundle:Concepto')->find($conceptoItemArray['concepto']['id']);
            $conceptoItem->setConcepto($concepto);
        }
        $conceptoItem->setImporte($conceptoItemArray['importe']);
        $conceptoItem->setPorcentaje($conceptoItemArray['porcentaje']);

        return $conceptoItem;
        }
}
