<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ConjuntoControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConjuntoControlRepository extends \Doctrine\ORM\EntityRepository
{
}
