<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * DomicilioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomicilioRepository extends \Doctrine\ORM\EntityRepository
{
    public function domicilioByOrganismo($idOrg) {
       
        $query = $this->getEntityManager()->createQuery(
        'SELECT d,l,de,td,p '
            . 'FROM SiafcaIntranetBundle:Domicilio d '
                . ' JOIN d.organismo o '
                . ' JOIN d.localidad l '
                . ' JOIN l.departamento de '
                . ' JOIN de.provincia p '
                . ' JOIN d.tipoDomicilio td '
            . ' WHERE o.id = :idOrganismo '
            . ' AND td.id = 2'    
        )
        ->setParameter('idOrganismo',$idOrg)
        ->getResult();
        
        return $query;
        
    }
}
