<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * EntidadResponsableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadResponsableRepository extends \Doctrine\ORM\EntityRepository
{
}
