<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EstadoCivilRepository extends \Doctrine\ORM\EntityRepository
{
    //put your code here
}
