<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ExcepcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcepcionRepository extends \Doctrine\ORM\EntityRepository
{
}
