<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ExpteAmparoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpteAmparoRepository extends \Doctrine\ORM\EntityRepository
{
}
