<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ExpteAmpItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpteAmpItemRepository extends \Doctrine\ORM\EntityRepository
{
}
