<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ExpteAmpItemConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpteAmpItemConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
