<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * FirmanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmanteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Obtiene el index de firmantes pendientes
     * @return lista
     */
    public function IndexFirmantesPendientes()
    {
        // ESTADO  ID 34 Creado
        //         ID 37 Rechazado
        $dql = "SELECT f,o,to,p,e "
                . " FROM SiafcaIntranetBundle:Firmante f "
                . " JOIN f.organismo o"
                . " JOIN o.tipoOrganismo to"
                . " JOIN f.persona p"
                . " JOIN f.estado e"
                . " WHERE f.estado IN(34,37)"
                . " ORDER BY e.nombre, o.nombre";
        
        return $this->getEntityManager()->createQuery($dql)->getResult();
    }
    
    /*
     * Obtiene la cantidad de firmantes pendientes
     * @return cantidad
     */
    public function cantidadFirmantesPendientes()
    {
        $dql = "SELECT COUNT(f) "
                . " FROM SiafcaIntranetBundle:Firmante f "
                . " WHERE f.estado =  34";
        
        return $this->getEntityManager()
                    ->createQuery($dql)->getSingleScalarResult();
    }
    
    /**
     * Obtiene el firmante activo de un organismo
     * @param int $idOrganismo
     * @return Firmante
     */
    public function getActive($idOrganismo)
    {
        $em = $this->getEntityManager();

        $activo = $em->createQuery(
            "SELECT f
             FROM SiafcaIntranetBundle:Firmante f
                JOIN f.organismo o
             WHERE o.id = :orgId
                AND f.fechaHasta IS NULL")
            ->setParameters( array('orgId' => $idOrganismo))->getResult();

        return $activo;
    }
    
     /**
     * Obtiene el firmante activo de un organismo
     * @param int $idOrganismo
     * @return Firmante
     */
    public function getMaximaFecha($idOrganismo)
    {
        $em = $this->getEntityManager();

        $fechamax = $em->createQuery(
            "SELECT MAX (f.fechaHasta)+1
             FROM SiafcaIntranetBundle:Firmante f
                JOIN f.organismo o
             WHERE o.id = :orgId "
            )
            ->setParameters( array('orgId' => $idOrganismo))
            ->getResult();

        return $fechamax;
    }
    
    public function getFirmantesByOrganismo($idOrganismo)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '.
                    'f, p '.
                'FROM '.
                    'SiafcaIntranetBundle:Firmante f '.
                    'JOIN f.persona p '.
                'WHERE '.
                    'f.organismo = :idOrganismo '.
                'ORDER BY '.
                    'f.fechaHasta desc, f.estado, p.apellidoPat ASC '
                )    
                ->setParameter('idOrganismo', $idOrganismo)
                ->getResult();  
       return $query;
       
    }
}
