<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * InformeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInformeItemSorted($informeId){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $query = $qb->select('c.codigo','c.nombre','ii.cantidad','ii.importeTotal','c.orden')
                ->from('SiafcaIntranetBundle:InformeItem','ii')
                ->join('ii.concepto','c')
                ->join('ii.informe','i')
                ->orderBy('c.orden')
                ->where('i.id='.$informeId);
        $informeItem = $query->getQuery()->getResult();

    
        return $informeItem;
    }
}
