<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * InformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *  Ejecuta el procedimiento almacenado que genera el informe de una Liquidación
     * @param int $idLiquidacion
     * @return int
     */
    public function generarInforme($idLiquidacion)
    {
        $em = $this->getEntityManager()->getConnection();
        
        $statement = 'BEGIN :return_value := SF_WS_INFORME('.$idLiquidacion.'); END;';
        $query = $em->prepare($statement);
        $query->bindParam(':return_value', $returnValue, SQLT_CHR, 1);
        $query->execute();
        
        return (int) $returnValue;
    }
}
