<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * NacionalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NacionalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
