<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * ParametrizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
