<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * PresentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentacionRepository extends \Doctrine\ORM\EntityRepository
{
}
