<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * SectorPasivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorPasivoRepository extends \Doctrine\ORM\EntityRepository
{
}
