<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * TipoOrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoOrganismoRepository extends \Doctrine\ORM\EntityRepository
{
}
