<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * TipoDomicilioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDomicilioRepository extends \Doctrine\ORM\EntityRepository
{
}
