<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * TipoDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
