<?php

namespace Caja\SiafcaIntranetBundle\Repository;

/**
 * TransicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransicionRepository extends \Doctrine\ORM\EntityRepository
{
}
