<?php

namespace Caja\SiafcaIntranetBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use \Caja\SiafcaIntranetBundle\Entity\Usuario;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username) 
    {
        if ($username instanceof Usuario) {
            $usuario = $this->findOneByUsername($username->getUsername());
        } else {
            $usuario = $this->findOneByUsername($username);
        }
        
        return $usuario;
    }
}